#define SECRET_SSID "WLAN"
#define SECRET_PASS "PASSWORD"
#define SECRET_MQTT_SERVER "server.lan"
#define MQTT_LOCATION "desk"
#define ENABLED_CO2 1
#define ENABLED_LIGHT 1
#define ENABLED_LED_CONTROL 0
#define ENABLED_TEMP 1
#define ENABLED_PIR 0
#define ENABLED_PRESSURE 0

